sudo: false
language: php

php:
  - 7.1
  - 7.2
  - nightly

before_install:
  - pecl install ast
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-clover ./tests/coverage/clover.xml
  - bin/behat
  - bin/phan

after_success:
  - travis_retry php bin/coveralls -v